version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "installing something"

  pre_build:
    commands:
      - echo "we are in the pre build phase"

  build:
    commands:
      - echo "we are in the build block"
      - echo "we will run some tests"
      - echo "<h1>Congratulations</h1>" > index.html
      - echo "Listing files..."
      - ls -l
      - echo "Showing file content..."
      - cat index.html
      - grep -iq "Congratulations" index.html  # ✅ THIS IS THE FIX

  post_build:
    commands:
      - echo "we are in the post build phase"

artifacts:
  files:
    - '**/*'

